### ISSUE TITLE
Crash when load schema

### ISSUE THREAD

**Issue by gengjiawen** [AEB-labs/graphql-weaver#3]
```
Error: Unexpected reference to type Ride
    at Transformer.findType (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:249:19)
    at Transformer.mapType (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:269:24)
    at /Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:487:59
    at Array.map (<anonymous>)
    at Transformer.transformUnionType (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:487:36)
    at Transformer.copyType (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:315:25)
    at Transformer.transformType (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:297:21)
    at Transformer.processType (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:290:40)
    at Transformer.transform (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:210:18)
    at Object.transformSchema (/Users/gengjiawen/Documents/schema-stitching-demo/node_modules/_graphql-weaver@0.9.1@graphql-weaver/src/graphql/schema-transformer.ts:185:24)
```

**Comment by Yogu** [comment]
Ah, thanks for the bug report! The problem were union types that were referencing types declared "earlier" for their type options. I fixed it by serializing object types before union types. Can you please try version 0.9.2?
